baseURL = '/'
languageCode = 'en-us'
title = 'Data Speculations: A National Forum'
copyright = 'Data Speculations. All rights reserved.'
theme = "gohugo-theme-ananke"
canonifyURLS = true
[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/_index.md'
  weight = 1
[[menu.main]]
  name = 'About'
  pageRef = '/About'
  weight = 2
[[menu.main]]
  name = 'Events'
  pageRef = '/Events'
  weight = 3
[[menu.main]]
  name = 'People'
  pageRef = '/people'
  weight = 4

